### ISSUE TITLE
Raspberry Pi install fails with "No package matching 'linux-headers-5.10.63-v8+' is available"

### ISSUE THREAD

**Issue by whalecoiner** [githubixx/ansible-role-wireguard#140]
Attempting to use this role on a Raspberry Pi 3 using a clean install of 64bit Raspberry Pi OS (Buster) results in the following:

```
fatal: [sleeperservice]: FAILED! => {"changed": false, "msg": "No package matching 'linux-headers-5.10.63-v8+' is available"}
```

My Kernel version:
```
$ uname -r
5.10.63-v8+
```

**Comment by whalecoiner** [comment]
Update: I refreshed the Pi with the 32bit version of Raspberry Pi OS and ran the role against it again. This succeeded. 🎉 

Looks like an issue with Buster-based 64 Bit Raspberry Pi OS.

**Comment by githubixx** [comment]
I'm sorry but I guess I can't help too much with that issue as I don't have a Raspberry Pi and AFAIK there is no easy way to test this setup with Molecule as I do with all the other distributions. The Raspbian code was contributed. So it's really only best effort. In general what I can tell you don't need the kernel headers anymore for Linux kernel >= 5.6 as with that one the `wireguard` module is already included.

There was also some effort to simplify the role for Raspbian for Bullseys but it's not finished yet: https://github.com/githubixx/ansible-role-wireguard/pull/119

If you're lucky it's already good enough to just remove this task from `tasks/setup-debian.yml` (right at the top):

```yaml
- name: Setup for Raspbian
  ansible.builtin.include_tasks:
    file: "setup-debian-raspbian.yml"
    apply:
      tags:
        - wg-install
  when: ansible_lsb.id is defined and ansible_lsb.id == "Raspbian"
  register: wireguard__register_raspbian_setup
  ```

In that case the "vanilla" Debian code should be executed and since Raspbian and Debain in most parts are quite similar it might work. But that's only a guess :shrug:
