### ISSUE TITLE
Using only wireguard_unmanaged_peers throw an error if not limiting the run to one host at a time

### ISSUE THREAD

**Issue by trunet** [githubixx/ansible-role-wireguard#165]
Following the discussions from here https://github.com/githubixx/ansible-role-wireguard/issues/144#issuecomment-1039683168

I'm doing what you proposed on your last comment, but I want to have full control because everything is on a hashicorp vault, and I use community.hashi_vault.vault_kv2_get to fetch my variables and set them as vars in my task.

My playbook looks like this:
```yaml
    - name: Get wireguard configuration from vault
      ansible.builtin.set_fact:
        vault_wireguard_config: "{{ lookup('community.hashi_vault.vault_kv2_get', inventory_hostname, engine_mount_point='wireguard').data.data }}"
    - name: Wireguard configuration
      ansible.builtin.include_role:
        name: githubixx.ansible_role_wireguard
      vars:
        wireguard_interface: "{{ wireguard_peers.key }}"
        wireguard_port: "{{ wireguard_peers.value.ListenPort }}"
        wireguard_address: "{{ wireguard_peers.value.AddressIPv4 }},{{ wireguard_peers.value.AddressIPv6 }}"
        wireguard_private_key: "{{ wireguard_peers.value.PrivateKey }}"
        wireguard_table: 'off'
        wireguard_postup:
          - "firewall-cmd --new-zone={{ wireguard_peers.key | replace('.', '-') }} --permanent"
          - "firewall-cmd --zone=trusted --add-interface {{ wireguard_peers.key }} --permanent"
          - "firewall-cmd --reload"
          - "firewall-cmd --zone={{ wireguard_peers.key | replace('.', '-') }} --add-source={{ wireguard_peers.value.EndPoint | split(':') | first }}/32"
          - "firewall-cmd --zone={{ wireguard_peers.key | replace('.', '-') }} --add-port={{ wireguard_peers.value.ListenPort }}/udp"
        wireguard_postdown:
          - "firewall-cmd --zone={{ wireguard_peers.key | replace('.', '-') }} --remove-port={{ wireguard_peers.value.ListenPort }}/udp"
          - "firewall-cmd --zone={{ wireguard_peers.key | replace('.', '-') }} --remove-source={{ wireguard_peers.value.EndPoint | split(':') | first }}/32"
          - "firewall-cmd --delete-zone={{ wireguard_peers.key | replace('.', '-') }} --permanent"
          - "firewall-cmd --zone=trusted --remove-interface {{ wireguard_peers.key }} --permanent"
          - "firewall-cmd --reload"
        wireguard_unmanaged_peers:
          "{{ wireguard_peers.key }}":
            public_key: "{{ wireguard_peers.value.EndPointPublicKey }}"
            preshared_key: "{{ wireguard_peers.value.PreSharedKey }}"
            endpoint: "{{ wireguard_peers.value.EndPoint }}"
            allowed_ips: "0.0.0.0/0,::/0"
      loop: "{{ vault_wireguard_config.Peers | dict2items }}"
      loop_control:
        loop_var: wireguard_peers
```

If I `--limit [ONE HOST]` it works, if I don't set, I get an error related to the public_key fact: 
https://github.com/githubixx/ansible-role-wireguard/blob/38210058397e74aa55b05c5832e6cb2e2f068c17/templates/etc/wireguard/wg.conf.j2#L47-L52

I don't know exactly how you want to address this use case, but it's definitely a use case for your awesole role here. I'm using but I have to limit one by one which is not ideal. I would say that you can add another variable called per example `wireguard_unmanaged_peers_only` and it would not go on this loop above.

I can send a PR if you agree with the approach or let me know if you can think on another approach.
