### ISSUE TITLE
How to use wireguard_dc?

### ISSUE THREAD

**Issue by sistason** [githubixx/ansible-role-wireguard#167]
Hi,

I can't seem to figure out how to use `wireguard_dc`. I presume it's supposed to work as a default?

I want to set a single `Endpoint` of a Peer to a custom port, for which `wireguard_dc` seems to be made (there is no other choice in wg.conf.j2).
I expected to set the vars of the host with the custom port to:
```
custom_host:
  ansible_host: "XXX.XXX.XXX.XXX"
  wireguard_dc:
    name: "nas behind portforwarding"
    endpoint: "XXX.XXX.XXX.XXX"
    port: 51830
```

But, since this is only formatted when `wireguard_dc` is also defined for _all_ hosts, I also need to put it into `all`-groupvars as:
```
wireguard_dc:
  name: "not nas"
  endpoint: "{{ ansible_host }}"
  port: "51820"
```

I don't want to use `wireguard_dc` for every host just to use it for one. Additionally, this prevents from having hosts with "no endpoint defined" (`wireguard_endpoint = ""`), as the wireguard_dc config will be templated for EVERY host and empty endpoint is not implemented there.

I need to be able to set one Endpoint to a custom port, but the `if` in wg.conf.j2#L61 is too strict for that. Is there another way to use a custom port or is the custom-port + undefined_endpoint-peer combination just something which never came up before and needs to be adapted? :)
