### ISSUE TITLE
Unraid support

### ISSUE THREAD

**Issue by cosandr** [githubixx/ansible-role-wireguard#173]
Hi,

I've forked this a while ago to add unraid support ([relevant commit](https://github.com/cosandr/ansible-role-wireguard/commit/631378a08703f66ccf8ff3ad04ab1bc3bf0db544)).

Would you be interested in a PR to upstream this? I'll clean it up a bit of course, but the gist is in that commit at least.

**Comment by githubixx** [comment]
Hello,

in general I'd have no problem in upstream this. Sadly there is no [unraid box](https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=libvirt&q=unraid) which can be used for Molecule. That makes it hard to test esp. when new features should be added in the future. Is there a compatible OS that can be used as a replacement maybe?

**Comment by cosandr** [comment]
It's based on Slackware, I see there's [one box](https://app.vagrantup.com/talosthoren/boxes/slackware64-14.2) available but I have no idea how similar it is. It would be minimal support (basically only configuration as installation is done through the GUI). I've also found a couple of quirks:
- DNS is broken, I couldn't get it to work. The tunnel is not created if you try to use it.
- `wireguard_interface` must be named `wg\d+` or it will not show up in the UI.
- Config files are stored in `/boot/config/wireguard` instead of `/etc/wireguard`. 
- No systemd, it uses `/etc/rc.d/rc.*` scripts. `/etc/rc.d/rc.wireguard` loops through all wireguard configs and runs a bunch of ip commands, looks messy. Again, this role should primarily be used to configure it, not manage the service.
- At least for my use-case, it is necessary to add
```yml
wireguard_postup:
  - logger -t wireguard 'Tunnel WireGuard-{{ wireguard_interface }} started'
  - iptables -t nat -A POSTROUTING -s "{{ wg_net.mt.cidr }}" -o br0 -j MASQUERADE
wireguard_postdown:
  - logger -t wireguard 'Tunnel WireGuard-{{ wireguard_interface }} stopped'
  - iptables -t nat -D POSTROUTING -s "{{ wg_net.mt.cidr }}" -o br0 -j MASQUERADE
```
where `wg_net.mt.cidr` is the CIDR of the wireguard network. The logger is optional, but the unraid config generator adds it so I also did that.
