### ISSUE TITLE
Support for mutliple wireguard vpn on same host.

### ISSUE THREAD

**Issue by pierreozoux** [githubixx/ansible-role-wireguard#25]
Ok, now I know it is a bit more I'm asking, but I really don't want to fork your project, and I'd prefer to collaborate here :)

Basically, We run on hetzner too, and we have a kubernetes cluster on baremetal instance, and we have ceph, and 10g net cards.
So I'd like one wireguard for kube, one for ceph frontend, and one for ceph backend.

I see how I can do it with your role, but it will not be backward compatible.

Basically:

```
#instance-1 host_var
wireguard:
 - wg0:
    - address: 10.0.0.1/24
       port: 51820
 - ceph-backend:
    - address: 10.0.1.1/24
       port: 51821
#instance-2 host_var
wireguard:
 - wg0:
    - address: 10.0.0.2/24
       port: 51820
 - ceph-backend:
    - address: 10.0.1.2/24
       port: 51821
```

And then I'd loop over these keys and derive the interface name from there.

What do you think? Can I PR? (I'll do it anyway for me ;) )

**Comment by githubixx** [comment]
You give me a hard time, man... :wink: This is a feature I already thought about since I started with that role but never had time to implement it. Well, yeah, then lets do it. Create the PR when you're ready. But we still need to find a way to prevent the execution of the new version of this role for people who already use the current version as they would basically destroy they setup otherwise if they just upgrade without reading the changelog (e.g. by checking the existence of `wireguard_address` variable and stop executing the role if this variable exists). Maybe I can provide some upgrade script...

**Comment by AnatomicJC** [comment]
Hi there, I forked this repo to implement this requirement too, for my personal needs.

I implemented it this way:

```
vpn:
  vars:
    wireguard_ansible_children_group_prefix: "childvpn"
  children:
    childvpn1:
      vars:
        childvpn1_interface: "wg1"
        childvpn1_port: 51821
      hosts:
        k8s-1:
          childvpn1_address: "10.9.0.101/24"
          wireguard_endpoint: "{{ ansible_default_ipv4.address }}"
        k8s-2:
          childvpn1_address: "10.9.0.102/24"
          wireguard_endpoint: "{{ ansible_default_ipv4.address }}"
        k8s-3:
          childvpn1_address: "10.9.0.103/24"
          wireguard_endpoint: "{{ ansible_default_ipv4.address }}"
    childvpn2:
      vars:
        childvpn2_interface: "wg2"
        childvpn2_port: 51822
      hosts:
        k8s-1:
          childvpn2_address: "10.10.0.101/24"
        k8s-2:
          childvpn2_address: "10.10.0.102/24"
        k8s-3:
          childvpn2_address: "10.10.0.103/24"
```
It is still a work in progress and I have only my free time to do it: https://github.com/AnatomicJC/ansible-role-wireguard

I will have a look at your implementation, I'm very interested about this :)
