### ISSUE TITLE
setup-debian.yml not able to setup debian but ubuntu instead ..

### ISSUE THREAD

**Issue by quabug** [githubixx/ansible-role-wireguard#5]
Debian script should be like this depend on [WireGuard doc](https://www.wireguard.com/install/)

```

- name: Setup WireGuard preference
  command: "printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' > /etc/apt/preferences.d/limit-unstable"
  tags:
    - wg-install

- name: Add WireGuard key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "8B48AD6246925553"
    state: present
  run_once: true
  tags:
    - wg-install

- name: Add WireGuard repository
  apt_repository:
    repo: "deb http://deb.debian.org/debian/ unstable main"
    state: present
    update_cache: yes
  run_once: true
  tags:
    - wg-install
```
