### ISSUE TITLE
Linux header installation fails on Raspberry pi

### ISSUE THREAD

**Issue by penguineer** [githubixx/ansible-role-wireguard#53]
Installation fails on Raspberry Pi with Raspbian : setup-debian.yml tries to install `"linux-headers-{{ dpkg_arch.stdout }}"`, however, in Raspbian the package is called linux-headers (without arch).

**Comment by penguineer** [comment]
Possible solutions:
* Make Raspbian provide a package linux-headers-armhf
* Create a role setup-raspbian that takes the Raspbian anomaly into account
* Change the Debian-Role to deal with missing arch headers and try `linux-headers` instead

**Comment by penguineer** [comment]
Apparently the Debian keys also need to be added, which is an argument towards adding a Raspbian-specific role

**Comment by githubixx** [comment]
As I don't use a Raspberry it's unlikely that I'll do any changes in this regard. But pull requests are welcome. I guess too that a Raspbian specific role would make sense.

**Comment by penguineer** [comment]
Thanks for your reply!

Apparently there are two issues at hand:
* Raspbian is identified as Debian (with the assumption, that `ansible_distribution` identifies the target system)
* but it does not provide `"linux-headers-{{ dpkg_arch.stdout }}"`

I tried to go with the following in the setup-debian role:
```yaml
- name: (Debian) Install kernel headers to compile Wireguard with DKMS
  block:
    - apt:
        name:
        - "linux-headers-{{ dpkg_arch.stdout }}"
        state: present
  rescue:
    - apt:
        name:
        - "linux-headers"
        state: present
```

However, this will still report a failure, as expected from the block/rescue construct (even though the result is installed kernel headers on both systems).

I will try to fix the issues on  the Raspbian side and/or find a less intrusive way to adapt the setup-debian role.
